/**
 * Stress fixture generator.
 *
 * Writes into the real WriteMd vault under `_stress/` and nothing else. The
 * fixtures are deterministic (seeded PRNG, fixed shape) so two runs measure
 * the same work, and every file is regenerated from scratch each time, so the
 * folder is safe to delete whenever.
 *
 *   node tests/stress/generate-vault.mjs            # default sizes
 *   node tests/stress/generate-vault.mjs --quick    # small sizes, for smoke runs
 *   node tests/stress/generate-vault.mjs --vault D  # override the vault root
 */
import { mkdirSync, rmSync, writeFileSync } from 'fs'
import { homedir } from 'os'
import { join } from 'path'

const args = process.argv.slice(2)
const quick = args.includes('--quick')
const vaultFlag = args.indexOf('--vault')
const VAULT =
  vaultFlag >= 0 && args[vaultFlag + 1]
    ? args[vaultFlag + 1]
    : join(homedir(), 'Documents', 'WriteMd Vault')
const ROOT = join(VAULT, '_stress')

/** mulberry32: tiny, seeded, good enough for fixture text. */
function rng(seed) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const WORDS = [
  'alpha','beta','gamma','delta','epsilon','zeta','eta','theta','iota','kappa','lambda','mu',
  'nu','xi','omicron','pi','rho','sigma','tau','upsilon','phi','chi','psi','omega','render',
  'parse','viewport','selection','decoration','transaction','listener','subscription','scroll',
  'measure','layout','paint','composite','raster','shader','buffer','texture','atlas','glyph',
  'metric','baseline','regression','fixture','harness','threshold','budget','latency','frame'
]

function sentence(r, words = 12) {
  const out = []
  for (let i = 0; i < words; i++) out.push(WORDS[Math.floor(r() * WORDS.length)])
  const s = out.join(' ')
  return s.charAt(0).toUpperCase() + s.slice(1) + '.'
}

function paragraph(r, sentences = 4) {
  const out = []
  for (let i = 0; i < sentences; i++) out.push(sentence(r))
  return out.join(' ')
}

function codeBlock(r, lines) {
  const out = ['```ts']
  for (let i = 0; i < lines; i++) {
    out.push(`export const value${i} = compute(${Math.floor(r() * 1000)}, '${WORDS[Math.floor(r() * WORDS.length)]}')`)
  }
  out.push('```')
  return out.join('\n')
}

function table(r, rows, cols) {
  const head = ['| ' + Array.from({ length: cols }, (_, c) => `col ${c}`).join(' | ') + ' |']
  const sep = ['|' + Array.from({ length: cols }, () => ' --- ').join('|') + '|']
  const body = []
  for (let i = 0; i < rows; i++) {
    body.push('| ' + Array.from({ length: cols }, () => WORDS[Math.floor(r() * WORDS.length)]).join(' | ') + ' |')
  }
  return [...head, ...sep, ...body].join('\n')
}

function write(name, content) {
  const path = join(ROOT, name)
  mkdirSync(join(path, '..'), { recursive: true })
  writeFileSync(path, content, 'utf-8')
  const bytes = Buffer.byteLength(content)
  console.log(`${name.padEnd(28)} ${(bytes / 1024).toFixed(0).padStart(9)} KB`)
  return bytes
}

/* -------------------------------------------------------------------------- */

rmSync(ROOT, { recursive: true, force: true })
mkdirSync(ROOT, { recursive: true })

write(
  'README.md',
  [
    '# Stress fixtures',
    '',
    'Generated by `node tests/stress/generate-vault.mjs`. Nothing here is hand written and',
    'nothing outside this folder is touched. Safe to delete at any time; the generator',
    'recreates it.',
    ''
  ].join('\n')
)

const r = rng(20240607)

// 1. One huge document: everything a real note mixes, at volume.
{
  const sections = quick ? 40 : 8000
  const out = ['# Huge document', '', paragraph(r), '']
  for (let i = 0; i < sections; i++) {
    out.push(`## Section ${i}`, '')
    out.push(paragraph(r, 6), '')
    if (i % 3 === 0) {
      out.push(`- ${sentence(r)}`, `- ${sentence(r)}`, `  - nested ${sentence(r, 6)}`, '')
    }
    if (i % 5 === 0) out.push(codeBlock(r, 12), '')
    if (i % 7 === 0) out.push(table(r, 8, 5), '')
    if (i % 11 === 0) out.push('```mermaid', 'graph TD', '  A-->B', '  B-->C', '```', '')
    if (i % 13 === 0) out.push('$$', '\\int_0^1 x^2 \\, dx = \\frac{1}{3}', '$$', '')
    if (i % 17 === 0) out.push(`> [!note]`, `> ${sentence(r)}`, '')
    if (i % 19 === 0) out.push(`- [ ] task ${i}`, `- [x] done ${i}`, '')
    if (i % 23 === 0) out.push(`See [[Huge document#Section ${i}]] and [[Many notes 0001]].`, '')
    if (i % 29 === 0) out.push(`A footnote reference.[^${i}]`, '', `[^${i}]: ${sentence(r)}`, '')
  }
  write('huge-single.md', `${out.join('\n')}\n`)
}

// 2. One enormous table: the cell widget path, at a size no real note reaches.
{
  const rows = quick ? 200 : 4000
  write('huge-table.md', `# Huge table\n\n${table(r, rows, 8)}\n`)
}

// 3. Many diagrams: Mermaid is the heaviest dependency in the app.
{
  const count = quick ? 6 : 60
  const out = ['# Many diagrams', '']
  for (let i = 0; i < count; i++) {
    out.push('```mermaid', 'graph TD', `  N${i}a-->N${i}b`, `  N${i}b-->N${i}c`, '```', '')
  }
  write('many-diagrams.md', `${out.join('\n')}\n`)
}

// 4. Pathological nesting: lists, quotes, emphasis.
{
  const out = ['# Deep nesting', '']
  for (let d = 1; d <= (quick ? 12 : 40); d++) {
    out.push(`${'  '.repeat(d)}- level ${d} ${sentence(r, 4)}`)
  }
  out.push('')
  for (let d = 1; d <= (quick ? 8 : 30); d++) {
    out.push(`${'> '.repeat(d)}quoted level ${d}`)
  }
  out.push('')
  out.push(`${'*'.repeat(quick ? 20 : 120)}emphasis${'*'.repeat(quick ? 20 : 120)}`)
  out.push(`${'_'.repeat(quick ? 20 : 120)}underscore${'_'.repeat(quick ? 20 : 120)}`)
  write('deep-nesting.md', `${out.join('\n')}\n`)
}

// 5. Very long lines: the classic line-index blowup.
{
  const lines = quick ? 4 : 20
  const width = quick ? 20000 : 200000
  const out = ['# Long lines', '']
  for (let i = 0; i < lines; i++) out.push(`${i}: ${'lorem ipsum dolor sit amet '.repeat(Math.ceil(width / 27)).slice(0, width)}`)
  write('long-lines.md', `${out.join('\n')}\n`)
}

// 6. Unicode: graphemes, offsets, and anything that assumes ASCII.
{
  const out = ['# Unicode', '']
  out.push('Emoji: ' + ['😀', '👩‍💻', '🇳🇬', '🏳️‍🌈', '👍🏽'].join(' ') + '')
  out.push('CJK: ' + '_WRITE_MD_STRESS_'.repeat(200) + '')
  out.push('RTL: ' + 'مرحبا بالعالم '.repeat(200) + '')
  out.push('Combining: ' + 'éàô '.repeat(500) + '')
  out.push('Zero width: ' + 'a‍b‌c﻿d'.repeat(500) + '')
  out.push('Surrogates: ' + '𠜎𡈽𩸽'.repeat(300) + '')
  write('unicode.md', out.join('\n') + '\n')
}

// 7. Link farm: decorations, backlinks, and the explorer all walk these.
{
  const count = quick ? 200 : 3000
  const out = ['# Link farm', '']
  for (let i = 0; i < count; i++) {
    out.push(`[[Many notes ${String((i % 900) + 1).padStart(4, '0')}]] and [md link](./many/folder-${i % 20}/note-${i}.md)`)
  }
  write('wiki-links.md', `${out.join('\n')}\n`)
}

// 8. A wide vault: explorer, recent files, search, session restore.
{
  const notes = quick ? 120 : 1500
  const folders = 20
  let written = 0
  let bytes = 0
  for (let i = 0; i < notes; i++) {
    const folder = join(ROOT, 'many', `folder-${i % folders}`)
    mkdirSync(folder, { recursive: true })
    const name = `note-${i}.md`
    const body = [
      `# Many notes ${String(i + 1).padStart(4, '0')}`,
      '',
      paragraph(r, 3),
      '',
      `- [ ] follow up ${i}`,
      `- [x] shipped ${i}`,
      '',
      `Related: [[Many notes ${String(((i + 7) % notes) + 1).padStart(4, '0')}]]`,
      ''
    ].join('\n')
    writeFileSync(join(folder, name), body, 'utf-8')
    written += 1
    bytes += Buffer.byteLength(body)
  }
  console.log(`${'many/* (notes)'.padEnd(28)} ${String(written).padStart(9)} files, ${(bytes / 1024).toFixed(0)} KB`)

  // One folder deeper than the explorer's row cap, so the summarized branch is
  // exercised rather than assumed.
  const bulk = quick ? 40 : 600
  const bulkDir = join(ROOT, 'many', 'bulk')
  mkdirSync(bulkDir, { recursive: true })
  for (let i = 0; i < bulk; i++) {
    const body = `# Bulk note ${i}\n\n${paragraph(r, 2)}\n`
    writeFileSync(join(bulkDir, `bulk-${String(i).padStart(4, '0')}.md`), body, 'utf-8')
  }
  console.log(`${'many/bulk/*'.padEnd(28)} ${String(bulk).padStart(9)} files in one folder`)
}

// 9. One file per parser extension, so a stress run also covers features.
write(
  'features-frontmatter.md',
  ['---', 'title: Stress frontmatter', 'tags: [stress, perf]', 'nested:', '  key: value', '---', '', '# Frontmatter', '', paragraph(r), ''].join('\n')
)
write(
  'features-math.md',
  ['# Math', '', '$$', '\\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}', '$$', '', 'Inline $E = mc^2$ and $\\sum_{i=1}^n i$.', ''].join('\n')
)
write(
  'features-tasks.md',
  ['# Tasks', '', ...Array.from({ length: quick ? 50 : 500 }, (_, i) => `- [${i % 3 === 0 ? 'x' : ' '}] task ${i}`), ''].join('\n')
)
write(
  'features-code.md',
  ['# Code blocks', '', codeBlock(r, quick ? 40 : 400), '', '```python', 'def stress():', '    return 42', '```', ''].join('\n')
)
write(
  'features-footnotes.md',
  ['# Footnotes', '', ...Array.from({ length: quick ? 20 : 200 }, (_, i) => `Claim ${i}[^${i}]`), '', ...Array.from({ length: quick ? 20 : 200 }, (_, i) => `[^${i}]: note ${i}`), ''].join('\n')
)
write(
  'features-callouts.md',
  ['# Callouts', '', ...['note', 'tip', 'warning', 'danger', 'info'].flatMap((k) => [`> [!${k}]`, `> ${sentence(r)}`, '']), ''].join('\n')
)
write(
  'features-images.md',
  ['# Images', '', ...Array.from({ length: quick ? 4 : 40 }, (_, i) => `![alt ${i}](${i % 2 ? '../_assets' : '.'}/image-${i}.png)`), ''].join('\n')
)

console.log(`\nroot: ${ROOT}`)