import { test, expect, type ElectronApplication, type Page } from '@playwright/test'
import { mkdirSync, statSync, writeFileSync } from 'fs'
import { homedir } from 'os'
import { join } from 'path'
import { makeFixture, launch, firstWindow } from './fixtures'

/**
 * Full-app stress sweep against the real vault.
 *
 * Fixtures live in `~/Documents/WriteMd Vault/_stress/` and are generated by
 * `node tests/stress/generate-vault.mjs`. Nothing outside `_stress/` is opened,
 * typed into, or written: every path used here is asserted to live under the
 * stress folder first, and the app gets a throwaway userData dir so the real
 * profile is untouched.
 *
 * What it measures:
 * - time to first paint per fixture (open cost, per file shape)
 * - long tasks while typing, scrolling, and rendering heavy widgets
 * - JS/native memory after opening many tabs
 * - cost of rendering the whole 1500-file vault tree
 *
 * Thresholds are deliberately loose (they catch order-of-magnitude
 * regressions, not a slow laptop). The printed table is the real artifact.
 */
const VAULT = join(homedir(), 'Documents', 'WriteMd Vault')
const STRESS = join(VAULT, '_stress')
const fixture = makeFixture('stress')

const FIXTURES = [
  'huge-single.md',
  'huge-table.md',
  'many-diagrams.md',
  'deep-nesting.md',
  'long-lines.md',
  'unicode.md',
  'wiki-links.md',
  'features-math.md',
  'features-tasks.md',
  'features-code.md',
  'features-footnotes.md',
  'features-callouts.md',
  'features-frontmatter.md'
]

const TIMEOUT = 180_000

/**
 * Setup budget for the hook below, which is not `TIMEOUT`.
 *
 * `test.describe.configure({ timeout })` sets the budget for tests, not for
 * hooks: a hook takes the config's global `timeout`, which is 30s here. This one
 * writes a 1500-note tree and a 6 MB note to disk, launches Electron, and reloads
 * the app against the result, so on a loaded CI runner it is nowhere near 30
 * seconds. Playwright kills the hook at the global budget and the run then
 * reports it as a spec failure with the real cause nowhere in sight.
 */
const SETUP_TIMEOUT = 900_000

/** Size on disk, for the auto-save scenario. */
function fileSize(path: string): number {
  try {
    return statSync(path).size
  } catch {
    return 0
  }
}

const hugePath = join(STRESS, 'huge-single.md')

/** Generous ceilings. A slow machine should not turn this red. */
const BUDGET = {
  openMs: 15_000,
  longTaskMs: 4_000,
  longTaskCount: 60,
  treeMs: 8_000,
  treeLongTaskMs: 4_000
}

/**
 * `long-lines.md` is 4 MB arranged as 20 lines of 200 000 characters. A single
 * line that long is one uninterruptible parse step inside Lezer, so its cost
 * is the engine's, not the app's, and it gets its own ceiling rather than
 * pretending to be the same shape as a normal note.
 */
const PATHOLOGICAL_BUDGET_MS = 12_000

type Metrics = {
  scenario: string
  ms: number
  longTasks: number
  worstTask: number
  memMB: number
}

const metrics: Metrics[] = []

test.describe.configure({ timeout: TIMEOUT })

test.describe('Stress sweep', () => {
  let app: ElectronApplication | undefined
  let window: Page

  test.beforeAll(async () => {
    // Raises this hook's own budget. See SETUP_TIMEOUT for why the config's
    // global 30s is not enough here.
    test.setTimeout(SETUP_TIMEOUT)
    const openTabs = FIXTURES.map((f) => join(STRESS, f))
    for (const p of openTabs) {
      if (!p.startsWith(STRESS)) throw new Error(`refusing to open ${p}`)
    }
    writeFileSync(
      join(fixture.userData, 'config.json'),
      JSON.stringify(
        {
          files: {
            vaultPath: VAULT,
            recentFiles: openTabs,
            openTabs,
            activeTabPath: openTabs[0]
          },
          appearance: { theme: 'dark', panelOrientation: 'horizontal' },
          editor: { autoSave: false }
        },
        null,
        2
      ),
      'utf-8'
    )
    app = await launch(fixture)
    window = await firstWindow(app!)
    // Long tasks are the honest version of "does this stutter": anything over
    // 50ms on the main thread is a dropped frame the user feels.
    await window.addInitScript(() => {
      const w = window as unknown as { __longTasks?: number[] }
      w.__longTasks = []
      try {
        new PerformanceObserver((list) => {
          for (const entry of list.getEntries()) w.__longTasks?.push(entry.duration)
        }).observe({ entryTypes: ['longtask'] })
      } catch {
        // longtask unsupported: metrics fall back to wall clock only
      }
    })
    await window.reload()
    // Generous, and the inner bound rather than the effective one: this boot has
    // to re-read a synthetic vault holding a 1500-note tree and a 6 MB note. It
    // boots, just not within Playwright's 5s default on a loaded CI runner.
    await expect(window.locator('writemd-top-bar')).toBeVisible({ timeout: 180_000 })
  })

  test.afterAll(async () => {
    // Same reason as the setup hook: closing the app and deleting a 1500-note
    // synthetic vault is not a 30-second job on Windows.
    test.setTimeout(SETUP_TIMEOUT)
    await app?.close()
    fixture.cleanup()
    mkdirSync(join(process.cwd(), 'test-results'), { recursive: true })
    writeFileSync(
      join(process.cwd(), 'test-results', 'stress-metrics.json'),
      JSON.stringify(metrics, null, 2),
      'utf-8'
    )
    console.log('\n=== stress metrics ===')
    console.log(
      ['scenario', 'ms', 'longTasks', 'worstTask', 'memMB']
        .map((h, i) => (i === 0 ? h.padEnd(34) : h.padStart(i === 1 ? 9 : 18)))
        .join('')
    )
    for (const m of metrics) {
      console.log(
        [
          m.scenario.padEnd(34),
          String(Math.round(m.ms)).padStart(9),
          String(m.longTasks).padStart(10),
          String(Math.round(m.worstTask)).padStart(10),
          m.memMB.toFixed(0).padStart(9)
        ].join('')
      )
    }
  })

  /** Wall clock plus the long tasks recorded since the last reset. */
  async function measure(scenario: string, fn: () => Promise<void>): Promise<Metrics> {
    await resetTasks()
    const started = Date.now()
    let failure: unknown = null
    try {
      await fn()
    } catch (err) {
      // Record the numbers even when the body failed: a scenario that blew its
      // budget is exactly the row worth reading.
      failure = err
    }
    const ms = Date.now() - started
    const { count, worst } = await readTasks()
    const memMB = await memoryMB()
    const m: Metrics = { scenario, ms, longTasks: count, worstTask: worst, memMB }
    metrics.push(m)
    if (failure) throw failure
    return m
  }

  async function resetTasks(): Promise<void> {
    await window.evaluate(() => {
      ;(window as unknown as { __longTasks?: number[] }).__longTasks = []
    })
  }

  async function readTasks(): Promise<{ count: number; worst: number }> {
    return window.evaluate(() => {
      const list = (window as unknown as { __longTasks?: number[] }).__longTasks ?? []
      return { count: list.length, worst: list.length ? Math.max(...list) : 0 }
    })
  }

  /** Native working set across all processes, which is what actually ships. */
  async function memoryMB(): Promise<number> {
    const metrics = await app!.evaluate(async ({ app: electronApp }) => {
      const all = electronApp.getAppMetrics()
      return all.reduce((sum, m) => sum + m.memory.workingSetSize, 0)
    })
    return metrics / 1024
  }

  /** Open a note by clicking its tab, waiting for the title bar to catch up. */
  async function openNote(name: string): Promise<void> {
    const tab = window.locator('writemd-tab', { hasText: name })
    await tab.first().click()
    await expect(window.locator('writemd-editor .cm-content')).toBeVisible()
    await expect(window.locator('writemd-doc-bar input[aria-label="Document title"]')).toHaveValue(
      name.replace(/\.md$/i, '')
    )
  }

  test('every fixture opens and paints inside budget', async () => {
    for (const name of FIXTURES) {
      const budget = name === 'long-lines.md' ? PATHOLOGICAL_BUDGET_MS : BUDGET.longTaskMs
      const m = await measure(`open ${name}`, () => openNote(name))
      expect(m.ms, `open ${name} took ${m.ms}ms`).toBeLessThan(BUDGET.openMs)
      expect(m.worstTask, `open ${name} blocked ${m.worstTask}ms`).toBeLessThan(budget)
    }
  })

  test('typing in the 6 MB document stays responsive', async () => {
    // Open outside the measurement: switching to a 6 MB note is its own cost and
    // folding it in would hide what typing actually does.
    await openNote('huge-single.md')
    await window.locator('.cm-content').first().click()
    await window.keyboard.press('Control+End')
    const m = await measure('type in huge-single', async () => {
      await window.keyboard.type('stress typing pass', { delay: 30 })
    })
    expect(m.worstTask, `typing blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
    expect(m.longTasks, `${m.longTasks} long tasks while typing`).toBeLessThan(BUDGET.longTaskCount)
  })

  test('typing in a 4000 row table stays responsive', async () => {
    await openNote('huge-table.md')
    await window.locator('.cm-content').first().click()
    await window.keyboard.press('Control+End')
    const m = await measure('type in huge-table', async () => {
      await window.keyboard.type('cell edit', { delay: 30 })
    })
    expect(m.worstTask, `typing blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('clicking inside a 4000 row table does not freeze the window', async () => {
    await openNote('huge-table.md')
    const m = await measure('click in huge-table', async () => {
      await window.locator('.cm-content').first().click({ timeout: 20_000 })
      await window.keyboard.press('Control+End')
    })
    expect(m.worstTask, `the click blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('60 mermaid diagrams render without stalling', async () => {
    await openNote('many-diagrams.md')
    const m = await measure('render diagrams', async () => {
      // Mermaid loads on first diagram, so the wait covers the dynamic import.
      await expect
        .poll(async () => window.locator('.cm-mermaid-widget svg').count(), { timeout: 60_000 })
        .toBeGreaterThan(0)
      const mounted = await window.locator('.cm-mermaid-widget').count()
      const drawn = await window.locator('.cm-mermaid-widget svg').count()
      console.log(`DIAGRAMS mounted=${mounted} drawn=${drawn}`)
      // Scrolling must keep producing diagrams without a stall.
      await window.locator('.cm-content').first().hover()
      for (let i = 0; i < 5; i++) await window.mouse.wheel(0, 2500)
      await expect
        .poll(async () => window.locator('.cm-mermaid-widget svg').count(), { timeout: 60_000 })
        .toBeGreaterThan(0)
    })
    expect(m.worstTask, `diagram rendering blocked ${m.worstTask}ms`).toBeLessThan(
      BUDGET.longTaskMs
    )
  })

  test('KaTeX and footnotes render in a large note', async () => {
    await openNote('huge-single.md')
    const m = await measure('render math and footnotes', async () => {
      await window.locator('.cm-content').first().hover()
      for (let i = 0; i < 6; i++) await window.mouse.wheel(0, 2000)
    })
    expect(m.worstTask, `scrolling past math blocked ${m.worstTask}ms`).toBeLessThan(
      BUDGET.longTaskMs
    )
  })

  test('the command palette opens and filters instantly', async () => {
    await openNote('huge-single.md')
    const m = await measure('open command palette', async () => {
      await window.keyboard.press('Control+p')
      const palette = window.locator('writemd-command-palette')
      await expect(palette).toBeVisible()
      await palette.locator('input').first().fill('ex')
      await expect
        .poll(async () => palette.locator('.item').count(), { timeout: 10_000 })
        .toBeGreaterThan(0)
      await window.keyboard.press('Escape')
    })
    expect(m.worstTask, `the palette blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('backlinks scan the whole vault', async () => {
    await openNote('huge-single.md')
    const m = await measure('scan backlinks over 1500 notes', async () => {
      await openSurface('Backlinks')
      const panel = window.locator('writemd-backlinks-panel')
      await expect(panel).toBeVisible()
      // The scan reads every note in the vault; it is done when the loading text
      // clears. `.empty-msg` is also the no-results state, so wait on the text.
      await expect
        .poll(() => panel.locator('.empty-msg').first().innerText(), { timeout: 180_000 })
        .not.toBe('Scanning for links.')
    })
    expect(m.ms, `backlink scan took ${m.ms}ms`).toBeLessThan(60_000)
  })

  test('find is usable in a huge note', async () => {
    await openNote('huge-single.md')
    const m = await measure('open find panel', async () => {
      await window.keyboard.press('Control+f')
      const panel = window.locator('writemd-find-panel')
      await expect(panel).toBeVisible()
      await window.keyboard.press('Escape')
    })
    expect(m.worstTask, `opening find blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('scrolling a 6 MB document does not block', async () => {
    await measure('scroll huge-single', async () => {
      await openNote('huge-single.md')
      await window.locator('.cm-content').first().hover()
      for (let i = 0; i < 10; i++) await window.mouse.wheel(0, 3000)
    })
    const m = metrics[metrics.length - 1]
    expect(m.worstTask, `scrolling blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('find across the 6 MB document returns', async () => {
    await measure('find in huge-single', async () => {
      await openNote('huge-single.md')
      await window.keyboard.press('Control+f')
      const panel = window.locator('writemd-find-panel')
      await expect(panel).toBeVisible()
      // Fill the field directly: keystrokes would race the panel's focus. Read the
      // count node, not innerText: the panel renders inside a shadow root and
      // innerText never sees it.
      await panel.locator('input').first().fill('measure')
      await expect(panel.locator('.match-count')).toHaveText(/\d+ of \d+/, { timeout: 30_000 })
    })
    const m = metrics[metrics.length - 1]
    expect(m.worstTask, `find blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  /**
   * Open a split-pane surface from a known state.
   *
   * The split button is a switch, not a menu, so a pane left open by an earlier
   * scenario has to be closed before the launcher will appear.
   */
  async function openSurface(label: string): Promise<void> {
    const toggle = window.locator('writemd-icon-button[title="Split view"]')
    const openPanes = window.locator(
      'writemd-surface-launcher, writemd-vault-explorer, writemd-backlinks-panel'
    )
    for (let i = 0; i < 3; i++) {
      if ((await openPanes.count()) === 0) break
      await toggle.click()
      await window.waitForTimeout(200)
    }
    const launcher = window.locator('writemd-surface-launcher')
    if ((await launcher.count()) === 0) await toggle.click()
    await expect(launcher).toBeVisible()
    await launcher.locator('.row', { hasText: label }).click()
  }

  test('the whole vault tree renders inside budget', async () => {
    // The loop's wall clock is mostly Playwright's per-click overhead, so the
    // numbers that matter are the slowest single expand and the worst task.
    let slowestExpand = 0
    await measure('render full vault tree', async () => {
      await openSurface('Files')
      const explorer = window.locator('writemd-vault-explorer')
      await expect(explorer).toBeVisible()
      // Expand one folder at a time with a fresh query each round. Clicking by
      // index walks off the end of a list that grows as folders open, and a
      // `data-path` selector breaks on Windows backslashes.
      for (let round = 0; round < 60; round++) {
        const next = explorer.locator('.node-row[data-action="dir"][aria-expanded="false"]').first()
        if ((await next.count()) === 0) break
        const started = Date.now()
        await next.click()
        slowestExpand = Math.max(slowestExpand, Date.now() - started)
      }
      await expect
        .poll(async () => explorer.locator('.node-row').count(), { timeout: 30_000 })
        .toBeGreaterThan(1000)
    })
    const m = metrics[metrics.length - 1]
    expect(m.worstTask, `tree render blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.treeLongTaskMs)
    // Per-click wall time is mostly Playwright re-resolving `.first()` across
    // thousands of rows, so it only has to catch a real hang.
    expect(slowestExpand, `slowest folder expand took ${slowestExpand}ms`).toBeLessThan(5_000)
  })

  test('a folder with 600 notes summarizes instead of rendering every row', async () => {
    const m = await measure('expand a 600-note folder', async () => {
      await openSurface('Files')
      const explorer = window.locator('writemd-vault-explorer')
      await expect(explorer).toBeVisible()
      // Walk down the chain: each folder only exists once its parent is open.
      for (const name of ['_stress', 'many', 'bulk']) {
        const row = explorer.locator('.node-row[data-action="dir"]', { hasText: name })
        await expect(row).toBeVisible()
        if ((await row.getAttribute('aria-expanded')) === 'false') await row.click()
      }
      // The cap replaces the overflow with one row that says how much is left.
      const more = explorer.locator('.more-row')
      await expect(more).toHaveCount(1)
      await expect(more).toContainText('600 total')
      const rowsBefore = await explorer.locator('.node-row').count()
      expect(rowsBefore).toBeLessThan(400)
      await more.click()
      await expect(more).toHaveCount(0)
    })
    expect(m.worstTask, `expanding the folder blocked ${m.worstTask}ms`).toBeLessThan(
      BUDGET.longTaskMs
    )
  })

  /**
   * Reading mode is live preview made read-only, so it renders the same widgets;
   * `contenteditable` is the honest difference between the two.
   */
  async function ensureLiveMode(): Promise<void> {
    const content = window.locator('.cm-content').first()
    if ((await content.getAttribute('contenteditable')) === 'false') {
      await window.locator('writemd-doc-bar [title="Toggle Reading / Live Mode"]').click()
      await expect(content).toHaveAttribute('contenteditable', 'true', { timeout: 15_000 })
    }
  }

  test('reading mode renders a 4000-row table without stalling', async () => {
    await openNote('huge-table.md')
    await expect(window.locator('.cm-live-table-wrap')).toBeVisible({ timeout: 30_000 })
    const content = window.locator('.cm-content').first()
    const toggle = window.locator('writemd-doc-bar [title="Toggle Reading / Live Mode"]')
    const m = await measure('reading mode on a 4000-row table', async () => {
      await toggle.click()
      await expect(content).toHaveAttribute('contenteditable', 'false', { timeout: 15_000 })
      await toggle.click()
      await expect(content).toHaveAttribute('contenteditable', 'true', { timeout: 15_000 })
    })
    expect(m.worstTask, `the mode switch blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('a wiki link in a 3000-link note resolves to its target', async () => {
    await openNote('wiki-links.md')
    // Wiki links are a live-preview decoration; reading mode shows the raw text.
    await ensureLiveMode()
    const m = await measure('follow a wiki link', async () => {
      const link = window.locator('.cm-wiki-link', { hasText: 'note-42' }).first()
      // Decorations are viewport-scoped, so the link has to be on screen. The
      // view keeps its scroll position across a tab switch.
      await window.locator('.cm-content').first().click()
      await window.keyboard.press('Control+Home')
      await expect(link).toBeVisible({ timeout: 20_000 })
      await link.click()
      await expect
        .poll(
          () => window.locator('writemd-doc-bar input[aria-label="Document title"]').inputValue(),
          { timeout: 15_000 }
        )
        .toBe('note-42')
    })
    expect(m.worstTask, `following the link blocked ${m.worstTask}ms`).toBeLessThan(
      BUDGET.longTaskMs
    )
  })

  test('a task checkbox toggles in a 500-task note', async () => {
    await openNote('features-tasks.md')
    const m = await measure('toggle a task checkbox', async () => {
      const box = window.locator('.cm-live-task-checkbox').first()
      await expect(box).toBeVisible()
      // Whichever state it starts in, one click has to flip it.
      const was = await box.getAttribute('aria-checked')
      await box.click()
      await expect(box).toHaveAttribute('aria-checked', was === 'true' ? 'false' : 'true', {
        timeout: 10_000
      })
    })
    expect(m.worstTask, `the checkbox blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('switching theme redraws the 6 MB note without stalling', async () => {
    await openNote('huge-single.md')
    const m = await measure('switch theme on 6 MB', async () => {
      await window.locator('writemd-icon-button[title="Settings"]').click()
      const modal = window.locator('writemd-settings-modal')
      await expect(modal).toBeVisible()
      await modal.locator('.nav-btn', { hasText: 'Appearance' }).click()
      await modal.locator('.theme-card, .font-card').first().waitFor({ timeout: 15_000 })
      await modal.locator('.theme-card').nth(3).click()
      await modal.locator('.back-btn').click()
      await expect(modal).toHaveCount(0)
    })
    expect(m.worstTask, `the theme switch blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('auto-save writes the 6 MB note without a false conflict', async () => {
    await openNote('huge-single.md')
    await window.locator('writemd-icon-button[title="Settings"]').click()
    const modal = window.locator('writemd-settings-modal')
    await expect(modal).toBeVisible()
    await modal.locator('.nav-btn', { hasText: 'Files' }).click()
    const toggle = modal.locator('.setting-row', { hasText: 'Auto-save' }).locator('button')
    if ((await toggle.getAttribute('aria-checked')) === 'false') await toggle.click()
    await modal.locator('.back-btn').click()

    const before = await fileSize(hugePath)
    await window.locator('.cm-content').first().click()
    await window.keyboard.press('Control+End')
    const m = await measure('auto-save a 6 MB note', async () => {
      await window.keyboard.type(' SAVED', { delay: 20 })
      await expect.poll(() => fileSize(hugePath), { timeout: 60_000 }).toBeGreaterThan(before)
      // The writer must not hear its own write back as an external change.
      await window.waitForTimeout(3000)
      await expect(window.locator('writemd-conflict-dialog')).toHaveCount(0)
    })
    expect(m.worstTask, `the save blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  test('the word count in the info pill stays correct and live', async () => {
    await openNote('features-tasks.md')
    const pill = window.locator('writemd-info-pill')
    await expect(pill).toBeVisible()
    const words = async (): Promise<number> => {
      // Inside the pill's shadow root, so read the node rather than innerText.
      const text = await pill.locator('.count-item').first().innerText()
      const m = /([\d,]+)\s+words/.exec(text)
      expect(m, `pill text was ${JSON.stringify(text)}`).not.toBeNull()
      return Number((m as RegExpExecArray)[1].replace(/,/g, ''))
    }
    // Debounced, so give it a moment rather than asserting the stale value.
    await expect.poll(words, { timeout: 10_000 }).toBeLessThan(50_000)
    const before = await words()
    await window.locator('.cm-content').first().click()
    await window.keyboard.press('Control+End')
    await window.keyboard.type(' extra words here', { delay: 20 })
    await expect.poll(words, { timeout: 10_000 }).toBeGreaterThan(before)
  })

  test('typing with 40 tabs open stays responsive', async () => {
    await window.locator('.cm-content').first().click()
    await window.keyboard.press('Control+End')
    const m = await measure('type with 40 tabs', async () => {
      await window.keyboard.type('tab pressure', { delay: 30 })
    })
    expect(m.worstTask, `typing blocked ${m.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
  })

  /**
   * Last, because it relaunches the app: the running instance persists its own
   * tab list, and a config written while it is alive gets overwritten by the
   * write it has already queued.
   */
  test('session restore with 40 tabs stays inside budget', async () => {
    // The generator puts note-N in folder-(N % 20); pair them that way, or the
    // path does not exist and restore correctly skips it.
    const manyNotes = Array.from({ length: 40 }, (_, i) => {
      const n = i * 7
      return join(STRESS, 'many', `folder-${n % 20}`, `note-${n}.md`)
    })
    for (const p of manyNotes) {
      if (!p.startsWith(STRESS)) throw new Error(`refusing to open ${p}`)
    }
    await app!.close()
    writeFileSync(
      join(fixture.userData, 'config.json'),
      JSON.stringify(
        {
          files: {
            vaultPath: VAULT,
            recentFiles: manyNotes,
            openTabs: manyNotes,
            activeTabPath: manyNotes[0]
          },
          appearance: { theme: 'dark', panelOrientation: 'horizontal' },
          editor: { autoSave: false }
        },
        null,
        2
      ),
      'utf-8'
    )
    const started = Date.now()
    app = await launch(fixture)
    window = await firstWindow(app!)
    await expect(window.locator('writemd-top-bar')).toBeVisible()
    await expect.poll(() => window.locator('writemd-tab').count(), { timeout: 60_000 }).toBe(40)
    const ms = Date.now() - started
    const memMB = await memoryMB()
    metrics.push({ scenario: 'restore 40 tabs', ms, longTasks: 0, worstTask: 0, memMB })

    await window.locator('.cm-content').first().click()
    await window.keyboard.press('Control+End')
    const typed = await measure('type with 40 tabs', async () => {
      await window.keyboard.type('tab pressure', { delay: 30 })
    })
    expect(typed.worstTask, `typing blocked ${typed.worstTask}ms`).toBeLessThan(BUDGET.longTaskMs)
    expect(ms, `restore took ${ms}ms`).toBeLessThan(60_000)
    expect(memMB, `working set ${memMB.toFixed(0)}MB`).toBeLessThan(2500)
  })
})
